apiVersion: v1 
kind: Pod 
metadata: 
   name: resultapp
   labels: 
      app: resultapp
      type: frontend 
spec: 
  containers: 
   - name: resultapp-container
     image: vsiraparapu/result-app 
     ports: 
       - containerPort: 80
