apiVersion: v1 
kind: Pod 
metadata: 
   name: voteapp
   labels: 
      app: voteapp
      type: frontend 
spec: 
  containers: 
   - name: voteapp-container
     image: vsiraparapu/voting-app 
     ports: 
       - containerPort: 80
